name: Sparse Checkout
on:
  push:
    branches: [ "master" ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .git
            packages
            excalidraw-app
          fetch-depth: 0
          ref: master

      - name: Run analyze
        run: npx @omlet/cli@0.0.0-staging-202502080531-138fcc analyze --dry-run